# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='default excerpt', max_length=255, verbose_name='Выдержка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='minutes_to_read',
            field=models.IntegerField(default=5, verbose_name='Minutes to read'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
